# print(type(15*3))
# print(type(15/3))
# print(type(15//3))
# print(type(15**2))
# a = (0, 'wee', [1, 2, 3],'er')
# print(type(a))

my_list = ['в ', '5', ' часов ', '17', ' минут ', 'температура ', 'воздуха ', 'была ', '+5', ' градусов']
# my_list.insert(1, '"')
# my_list.insert(3, '"')
# my_list.insert(5, '"')
# my_list.insert(7, '"')
# my_list.insert(12, '"')
# my_list.insert(14, '"')
my_list.insert(my_list.index('+5'), '"')
my_list.insert(my_list.index('+5')+1, '"')
# my_list[3].extend(['"'])
# my_list[1].extend(['"'])
# print(my_list.index('+5'))
print(my_list)
print(''.join(my_list))